[project]
name = "psl-project3"
version = "0.1.0"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "nltk>=3.9.1",
    "polars>=1.17.1",
    "scikit-learn>=1.6.0",
    "sentence-transformers>=3.3.1",
]
